import fs from "node:fs/promises";
import path from "node:path";
import kleur from "kleur";
import { bootstrapReportSchema, type BootstrapReport } from "@studioflow/contracts";
import { resolveFromWorkspace, workspaceRoot } from "./path-utils.js";

type PackageManager = BootstrapReport["packageManager"];
type ProjectType = BootstrapReport["projectType"];

async function detectPackageManager(root: string): Promise<PackageManager> {
  const lockfiles: Array<{ manager: PackageManager; file: string }> = [
    { manager: "pnpm", file: "pnpm-lock.yaml" },
    { manager: "npm", file: "package-lock.json" },
    { manager: "yarn", file: "yarn.lock" }
  ];

  for (const lock of lockfiles) {
    try {
      await fs.access(path.join(root, lock.file));
      return lock.manager;
    } catch {
      // Continue checking.
    }
  }

  return "unknown";
}

async function walk(dir: string, acc: string[] = []) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (["node_modules", ".next", ".git", "dist", ".runs"].includes(entry.name)) continue;
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(fullPath, acc);
    } else {
      acc.push(fullPath);
    }
  }
  return acc;
}

function detectProjectType(pkg: Record<string, unknown>, files: string[]): ProjectType {
  const deps = {
    ...(typeof pkg.dependencies === "object" && pkg.dependencies ? (pkg.dependencies as Record<string, unknown>) : {}),
    ...(typeof pkg.devDependencies === "object" && pkg.devDependencies
      ? (pkg.devDependencies as Record<string, unknown>)
      : {})
  };

  if (deps.next || files.some((file) => file.includes("/app/") && file.endsWith("/page.tsx"))) {
    return "nextjs";
  }
  if (deps.vite && deps.react) {
    return "vite-react";
  }
  return "unknown";
}

function chooseStartCommand(
  pkg: Record<string, unknown>,
  packageManager: PackageManager
): { command: string; note?: string } {
  const scripts =
    typeof pkg.scripts === "object" && pkg.scripts ? (pkg.scripts as Record<string, unknown>) : ({} as Record<string, unknown>);
  const pmRun = packageManager === "npm" ? "npm run" : packageManager === "yarn" ? "yarn" : "pnpm";

  if (typeof scripts["dev:sample"] === "string") return { command: `${pmRun} dev:sample` };
  if (typeof scripts.dev === "string") return { command: `${pmRun} dev` };
  if (typeof scripts.start === "string") return { command: `${pmRun} start` };

  return { command: "pnpm dev", note: "Fallback start command used because package scripts were not detected." };
}

function defaultHealthPath(projectType: ProjectType) {
  if (projectType === "nextjs") return "/api/health";
  return "/";
}

export async function bootstrapCommand(outPath = "artifacts/bootstrap.json") {
  const root = workspaceRoot();
  const pkgPath = path.join(root, "package.json");
  const pkg = JSON.parse(await fs.readFile(pkgPath, "utf8"));
  const packageManager = await detectPackageManager(root);
  const files = await walk(root);
  const projectType = detectProjectType(pkg, files);
  const chosen = chooseStartCommand(pkg, packageManager);
  const healthPath = defaultHealthPath(projectType);

  const report: BootstrapReport = {
    generatedAt: new Date().toISOString(),
    projectRoot: root,
    packageManager,
    projectType,
    startCommand: chosen.command,
    healthPath,
    notes: [
      "Generated by studioflow bootstrap.",
      "Override runtime values with .studioflow/config.json or run command flags.",
      ...(chosen.note ? [chosen.note] : [])
    ]
  };

  const validated = bootstrapReportSchema.parse(report);
  const resolved = resolveFromWorkspace(outPath);
  await fs.mkdir(path.dirname(resolved), { recursive: true });
  await fs.writeFile(resolved, JSON.stringify(validated, null, 2), "utf8");

  console.log(kleur.green("Bootstrap report generated."));
  console.log(`- Output: ${resolved}`);
  console.log(`- Start command: ${validated.startCommand}`);
  console.log(`- Health path: ${validated.healthPath}`);
}
